name: flutter_gitser
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # * Floor Database
  floor: ^1.4.2

  # * Dependency Injection
  get_it: ^7.6.7

  # * Business Login Component
  flutter_bloc: ^8.1.4

  # * Image Loading URL
  cached_network_image: ^3.3.1

  # * JSON Serializeable
  json_annotation: ^4.8.1

  # * Working With API
  retrofit: ^4.1.0
  dio: ^5.4.1

  # * Google Fonts
  google_fonts: ^6.1.0

  # * Toast
  fluttertoast: ^8.2.4

  # * Simple Data Persistent
  shared_preferences: ^2.2.2

  # * Simplify Object Comparison
  equatable: ^2.0.5

  # * Hooks
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  floor_generator: ^1.4.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
